server:
  port : 8083
  servlet:
    context-path: /flavor-api

spring:
  data:
    mongodb:
      uri: mongodb://admin:password@10.0.0.0:27017/test?authSource=admin&retryWrites=true&w=majority

  config:
    activated:
      on-profile: dev

logging:
  level:
    root: INFO