
version: "3"
services:
  mongo:
    image: mongo
    ports:
      - 27017-27020:27017-27020
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - mongo-compose-network

  flavor-api:
    container_name: flavor-api
    image: flavor-api:0.0.1-SNAPSHOT
    ports:
      - 8085:8085
    environment:
      SPRING_PROFILES_ACTIVE: dev
      TZ: "America/São Paulo"
    depends_on:
      - mongo

networks:
  mongo-compose-network:
    driver: bridge