version: "3"
services:
  mongo:
    image: mongo
    ports:
      - 27017-27020:27017-27020
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - docker-network

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    restart: always
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
    networks:
      - docker-network

  flavor-api:
    container_name: flavor-api
    image: flavor-api:0.0.1-SNAPSHOT
    ports:
      - 8083:8083
    environment:
      SPRING_PROFILES_ACTIVE: dev
      TZ: "America/São Paulo"
    depends_on:
      - mongo
    networks:
      - docker-network
    deploy:
      resources:
        limits:
          memory: 700M
        reservations:
          memory: 700M
    restart: always

networks:
  docker-network:
    driver: bridge